version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install pytest coverage boto3
  
  pre_build:
    commands:
      - echo "Running Combined AI Analysis (Basic + Bedrock + CodeWhisperer)..."
  
  build:
    commands:
      - echo "[STEP 1] Combined AI Analysis"
      - python combined_ai_analyzer.py
      - echo ""
      - echo "[STEP 2] Running Tests with Coverage"
      - coverage run -m pytest tests/
      - coverage json -o coverage.json || coverage report
  
  post_build:
    commands:
      - echo ""
      - echo "=========================================="
      - echo "BUILD COMPLETED - Combined AI Analysis"
      - echo "=========================================="
      - echo "Results:"
      - test -f combined_analysis.json && cat combined_analysis.json | head -20 || echo "No combined analysis"
      - echo ""
      - echo "Coverage:"
      - test -f coverage.json && echo "Coverage report generated" || echo "No coverage report"

artifacts:
  files:
    - coverage.json
    - combined_analysis.json
    - security-report.json
    - bedrock_analysis.json
    - tests/**/*
